# yamllint disable rule:brackets rule:colons rule:line-length
# This workflow integrates ShiftLeft NG SAST with GitHub
# Visit https://docs.shiftleft.io for help
name: shiftleft-go-repository-job

on:   # yamllint disable-line rule:truthy
  push:
    branches:
      - main
      - master
  pull_request:
    types:
      - opened
      - edited
      - synchronize
  schedule:
    # * is a special character in YAML so you have to quote this string
    # schedule a job to run every day at 17:30 UTC
    - cron: '30 17 * * *'



jobs:
  shiftleft-go:
    name: shiftleft-go-internal-job
    timeout-minutes: 10
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/honestbank
      APOLLO_KEY: ${{ secrets.APOLLO_KEY }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.18"

      - name: Configure ssh-key for private modules
        env:
          SSH_KEY: ${{ secrets.ENGINEERING_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh; echo "$SSH_KEY" > ~/.ssh/id_rsa; chmod 600 ~/.ssh/id_rsa; git config --global url."git@github.com:".insteadOf "https://github.com/"
      - name: Download dependencies
        run: make generate

      - name: Download the ShiftLeft CLI and set permissions
        run: |
          curl https://cdn.shiftleft.io/download/sl > ${GITHUB_WORKSPACE}/sl && chmod a+rx ${GITHUB_WORKSPACE}/sl
      # ShiftLeft requires Java 1.8
      - name: Set up Java
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: NextGen Static Analysis
        run: ${GITHUB_WORKSPACE}/sl analyze --strict --wait --app ${{ github.event.repository.name }} --tag branch=${{ github.head_ref || steps.extract_branch.outputs.branch }} --go --cpg $(pwd)
        env:
          SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}

      - name: Build Rules V2
        run: |
          echo "---
          build_rules:
            - id: allow-zero-high-vulnerabilities
              finding_types:
                - '*'
              cvss_31_severity_ratings:
                - high
                - critical
              threshold: 0
              options:
                num_findings: 100
          " > shiftleft.yml;
      - name: NextGen Static Check-Analysis
        run: ${GITHUB_WORKSPACE}/sl check-analysis --v2 --app ${{ github.event.repository.name }} --config shiftleft.yml
        env:
          SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
